# Generated by Django 4.1.2 on 2022-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safewheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_arquit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_comunic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_instrument',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_metod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='acess_transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='banheiro_adapt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='barras_de_apoio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='horario',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='rampa_para_acesso',
            field=models.BooleanField(default=False),
        ),
    ]
